// Buddhist quotes for cycling in the quote box
const rdQuotes = [
  { text: "You are not the darkness you endured. You are the light that refused to surrender.", author: "John Mark Green" },
  { text: "Peace comes from within. Do not seek it without.", author: "The Buddha" },
  { text: "No one saves us but ourselves. No one can and no one may. We ourselves must walk the path.", author: "The Buddha" },
  { text: "Let go of what has passed. Let go of what may come. Let go of what is happening now.", author: "Ajahn Chah" },
  { text: "If your compassion does not include yourself, it is incomplete.", author: "Jack Kornfield" },
  { text: "The root of suffering is attachment.", author: "The Buddha" },
  { text: "Be where you are; otherwise you will miss your life.", author: "Jack Kornfield" },
  { text: "Hatred does not cease by hatred, but only by love; this is the eternal rule.", author: "The Buddha" },
  { text: "When you realize how perfect everything is, you will tilt your head back and laugh at the sky.", author: "The Buddha" },
  { text: "Awareness is the greatest agent for change.", author: "Eckhart Tolle" },
  { text: "Meditate. Live purely. Be quiet. Do your work with mastery. Like the moon, come out from behind the clouds! Shine.", author: "The Buddha" },
  { text: "The trouble is, you think you have time.", author: "Jack Kornfield (attributed to the Buddha)" },
  { text: "Three things cannot be long hidden: the sun, the moon, and the truth.", author: "The Buddha" },
  { text: "May all beings be happy; may all beings be without disease.", author: "Metta Sutta" },
  { text: "Don’t move. Just die over and over. Don’t anticipate. Nothing can save you now, because you have only this moment.", author: "Shunryu Suzuki" },
  { text: "Feelings come and go like clouds in a windy sky. Conscious breathing is my anchor.", author: "Thich Nhat Hanh" },
  { text: "Only the present moment contains life.", author: "Thich Nhat Hanh" },
  { text: "Try to be mindful. And let things take their natural course. Then your mind will become still in any surroundings, like a clear forest pool.", author: "Ajahn Chah" },
  { text: "You can’t stop the waves, but you can learn to surf.", author: "Jon Kabat-Zinn" },
  { text: "Nothing ever goes away until it has taught us what we need to know.", author: "Pema Chödrön" },
  { text: "To understand everything is to forgive everything.", author: "The Buddha" },
  { text: "Each morning we are born again. What we do today is what matters most.", author: "The Buddha" },
  { text: "As you walk and eat and travel, be where you are. Otherwise you will miss most of your life.", author: "The Buddha" },
  { text: "Don’t believe everything you think.", author: "Allan Lokos" },
  { text: "Forgive others not because they deserve forgiveness, but because you deserve peace.", author: "The Buddha (attributed)" },
  { text: "Recovery is not a path back to what was, but a doorway into what is possible.", author: "Unknown" },
  { text: "To be beautiful means to be yourself. You don’t need to be accepted by others. You need to accept yourself.", author: "Thich Nhat Hanh" },
  { text: "Breathe. Let go. And remind yourself that this very moment is the only one you know you have for sure.", author: "Oprah Winfrey" },
  { text: "The mind is everything. What you think, you become.", author: "The Buddha" },
  { text: "Be patient with all that is unresolved in your heart, and try to love the questions themselves.", author: "Rainer Maria Rilke" },
  { text: "The moment you see how important it is to love yourself, you will stop making others suffer.", author: "Thich Nhat Hanh" },
  { text: "If we are not fully ourselves, truly in the present moment, we miss everything.", author: "Thich Nhat Hanh" },
  { text: "The one who awakens shines radiantly. Their mind is at peace and their heart full of joy.", author: "The Dhammapada" },
  { text: "All conditioned things are impermanent—when one sees this with wisdom, one turns away from suffering.", author: "The Buddha" },
  { text: "You only lose what you cling to.", author: "The Buddha" },
  { text: "It is better to conquer yourself than to win a thousand battles.", author: "The Buddha" },
  { text: "All that we are is the result of what we have thought.", author: "The Buddha" },
  { text: "Just as a candle cannot burn without fire, men cannot live without a spiritual life.", author: "The Buddha" },
  { text: "This existence of ours is as transient as autumn clouds.", author: "The Buddha" },
  { text: "Whatever has the nature of arising also has the nature of ceasing.", author: "The Buddha" },
  { text: "Form is emptiness, emptiness is form.", author: "The Heart Sutra" },
  { text: "There is no path to happiness: happiness is the path.", author: "The Buddha" },
  { text: "Awakening is not changing who you are, but discarding who you are not.", author: "Deepak Chopra" },
  { text: "When you realize nothing is lacking, the whole world belongs to you.", author: "Lao Tzu" },
  { text: "The source of all pain is craving.", author: "The Buddha" },
  { text: "No self, no problem.", author: "Bodhidharma (modern phrasing)" },
  { text: "Letting go gives us freedom, and freedom is the only condition for happiness.", author: "Thich Nhat Hanh" },
  { text: "The mind is like water. When it is turbulent, it’s difficult to see. When it’s calm, everything becomes clear.", author: "The Buddha (attributed)" },
  { text: "When the ego dies, the soul awakens.", author: "Unknown" },
  { text: "Enlightenment is when a wave realizes it is the ocean.", author: "Thich Nhat Hanh" },
  { text: "There is no fire like passion, no shark like hatred, no snare like folly, no torrent like craving.", author: "The Dhammapada" },
  { text: "Those who are awake live in a constant state of amazement.", author: "Jack Kornfield" },
  { text: "Craving leads to suffering. Release leads to peace.", author: "The Buddha (summary paraphrase)" },
  { text: "Don’t seek the truth. Just cease to cherish opinions.", author: "Seng-ts’an" },
  { text: "Everything is created by mind. One who speaks or acts with a pure mind creates happiness.", author: "The Dhammapada" },
  { text: "There is nothing more dreadful than the habit of doubt.", author: "The Buddha" },
  { text: "The illusion of self is the root of all conflict.", author: "The Buddha (paraphrased)" },
  { text: "Emptiness is not nothingness. It is the fullness of possibility.", author: "Nagarjuna (modern interpretation)" },
  { text: "An awakened mind is not attached to anything, not even awakening.", author: "Dzogchen Ponlop Rinpoche" },
  { text: "The past no longer is, the future has not yet come. Look deeply at life as it is.", author: "The Buddha" },
  { text: "Don’t get lost in your pain, know that one day your pain will become your cure.", author: "Rumi" },
  { text: "Try not to resist the changes that come your way. Instead, let life live through you.", author: "Rumi" },
  { text: "Be like a tree and let the dead leaves drop.", author: "Rumi" },
  { text: "These pains you feel are messengers. Listen to them.", author: "Rumi" },
  { text: "With life as short as a half-taken breath, don’t plant anything but love.", author: "Rumi" },
  { text: "You were born with wings, why prefer to crawl through life?", author: "Rumi" },
  { text: "As you start to walk the way, the way appears.", author: "Rumi" },
  { text: "What you seek is seeking you.", author: "Rumi" },
  { text: "If you are distressed by anything external, the pain is not due to the thing itself, but to your estimate of it.", author: "Marcus Aurelius" },
  { text: "He is a wise man who does not grieve for the things which he has not, but rejoices for those which he has.", author: "Epictetus" },
  { text: "Man is not worried by real problems so much as by his imagined anxieties about real problems.", author: "Epictetus" },
  { text: "We suffer more often in imagination than in reality.", author: "Seneca" },
  { text: "It is not death that a man should fear, but he should fear never beginning to live.", author: "Marcus Aurelius" },
  { text: "To love only what happens, what was destined. No greater harmony.", author: "Marcus Aurelius" },
  { text: "Don’t seek for everything to happen as you wish it would, but rather wish that everything happens as it actually will—then your life will flow well.", author: "Epictetus" },
  { text: "You become what you give your attention to.", author: "Epictetus" },
  { text: "The happiness of your life depends upon the quality of your thoughts.", author: "Marcus Aurelius" },
  { text: "If you want to improve, be content to be thought foolish and stupid.", author: "Epictetus" },
  { text: "The impediment to action advances action. What stands in the way becomes the way.", author: "Marcus Aurelius" },
  { text: "Life always gives us exactly the teacher we need at every moment. This includes every mosquito, every misfortune, every red light, every traffic jam, every obnoxious supervisor (or employee), every illness, every loss, every addiction, every piece of garbage, every breath.", author: "Charlotte Joko Beck" },
  { text: "The wound is the place where the Light enters you.", author: "Rumi" },
  { text: "The only lasting beauty is the beauty of the heart.", author: "Rumi" },
  { text: "When the soul lies down in that grass, the world is too full to talk about ideas, language, even the phrase each other doesn’t make any sense.", author: "Rumi" },
  { text: "The only way to deal with fear is to face it head on.", author: "Pema Chödrön" },
  { text: "When you let go of what you are, you become what you might be.", author: "Lao Tzu" },
  { text: "The quieter you become, the more you can hear.", author: "Ram Dass" },
  { text: "You are not a drop in the ocean. You are the entire ocean in a drop.", author: "Rumi" },
  { text: "The function of prayer is not to influence God, but rather to change the nature of the one who prays.", author: "Søren Kierkegaard" },
  { text: "The only Zen you find on the tops of mountains is the Zen you bring up there.", author: "Robert M. Pirsig" },
  { text: "I would rather have questions that cannot be answered than answers that cannot be questioned.", author: "Richard Feynman" },
  { text: "Every morning we are born again. What we do today is what matters most.", author: "Buddha" },
  { text: "You can't go back and change the beginning, but you can start where you are and change the ending.", author: "C.S. Lewis" },
  { text: "We are what we repeatedly do... therefore excellence is not an act, but a habit.", author: "Will Durant" },
  { text: "Knowing how to think empowers you far beyond those who only know what to think.", author: "Neil deGrasse Tyson" },
  { text: "Between stimulus and response there is a space. In that space is our power to choose our response. In our response lies our growth and our freedom.", author: "Victor Frankl" },
  { text: "I am an old man and have known a great many troubles, but most of them never happened.", author: "Mark Twain" },
  { text: "The greatest glory in living lies not in never falling, but in rising every time we fall.", author: "Nelson Mandela" },
  { text: "I prayed for change, so, I changed my mind. I prayed for guidance and learned to trust myself. I prayed for happiness and realized I am not my ego. I prayed for peace and learned to accept others unconditionally. I prayed for abundance and realized my doubt kept it out. I prayed for wealth and realized it is my health. I prayed for a miracle and realized I am the miracle. I prayed for a soul mate and realized I am with the One. I prayed for love and realized it is always knocking, but I have to allow it in.", author: "Rumi" },
  { text: "Wherever there is a human being, there is an opportunity for kindness.", author: "Seneca" },
  { text: "I always get to where I am going by walking away from where I have been.", author: "Winnie the Pooh" },
  { text: "God is a metaphor for that which transcends all levels of intellectual thought. It's as simple as that.", author: "Joseph Campbell" },
  { text: "God is the name of the blanket we throw over the mystery to give it shape.", author: "Barry Taylor" },
  { text: "You can fall apart and still come back. You can relapse and still recover. You can lose your way and still find meaning.", author: "Unknown" },
  { text: "You can search the entire universe and not find a single being more deserving of love than yourself.", author: "Buddha (paraphrased)" },
  { text: "Let go or be dragged.", author: "Unknown (Zen Saying)" }
];

function cycleRDQuotes() {
  const box = document.getElementById('rd-quote-box');
  if (!box) return;
  let idx = Math.floor(Math.random() * rdQuotes.length);
  function showQuote(i) {
    box.innerHTML = `<em>“${rdQuotes[i].text}”</em><br>— ${rdQuotes[i].author}`;
  }
  showQuote(idx);
  setInterval(() => {
    idx = (idx + 1) % rdQuotes.length;
    showQuote(idx);
  }, 30000);
}

document.addEventListener('DOMContentLoaded', cycleRDQuotes);
