# Jekyll configuration for Recovery Dharma Vermont

# Site settings
title: "Recovery Dharma Vermont"
description: "A community for Recovery Dharma in Vermont. Meetings, meditation events, resources, and contact info."
url: "https://rdvt.org"
baseurl: ""
og_image: /assets/images/rd-icons/rdvt-icon.webp
tagline: "Buddhist-inspired recovery in Vermont"
social:
  name: "Recovery Dharma Vermont"
  image: /assets/images/rd-icons/rdvt-icon.webp
  links:
    - https://rdvt.org

# Theme settings
remote_theme: "mmistakes/minimal-mistakes@4.27.3"
minimal_mistakes_skin: "zen"
plugins:
  - jekyll-remote-theme
  - jekyll-data
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache

# Navigation
navigation:
  - title: "Home"
    url: "/"
  - title: "Meetings"
    url: "/meetings/"
  - title: "Meditation Events"
    url: "/meditation-events/"
  - title: "Resources"
    url: "/resources/"
  - title: "Buddhist Foundations"
    url: /buddhist-foundations/
  - title: "Contact"
    url: "/contact/"

# Collections
collections:
  pages:
    output: true
    permalink: /:path/

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: single
      author_profile: false
      classes: wide
      css: "custom"

  - scope:
      path: ""
      type: "posts"
    values:
      layout: single
      author_profile: false
      classes: wide
      css: "custom"
  
# Markdown & formatting
markdown: kramdown
kramdown:
  input: GFM

# Exclude
exclude:
  - README.md
  - RecoveryDharmaBVT/README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - theme-temp
